spring:
  data:
    mongodb:
      database: library_zhegalov
      uri: mongodb://172.17.0.3


server:
  port: 8081
  error:
    include-stacktrace: always

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.hw.changelog

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    ru.otus.spring.hw: INFO
    org.mongodb.driver: INFO
