spring:
  data:
    mongodb:
      database: library_zhegalov
      uri: mongodb://localhost

server:
  port: 8081
  error:
    include-stacktrace: always

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.hw.changelog

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    ROOT: DEBUG
    org.springframework: DEBUG
    ru.otus.spring.hw: DEBUG
    org.mongodb.driver: DEBUG
