spring:
  shell:
    interactive:
      enabled: true
  data:
    mongodb:
      # port: 0
      database: library
      uri: mongodb://172.17.0.3
      # port: 27017
mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.hw.changelog

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    ru.otus.spring.hw: DEBUG
