spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  flyway:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
    port: 8083

logging:
  level:
    ROOT: INFO
