version: "3"
services:
  backend:
    build: ./backend/
    ports:
      - "8081:8083"
    networks:
      - db
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017
    links:
      - mongo
  mongo:
    image: "mongo:4.4.4"
    networks:
      - db
    ports:
      - "27017:27017"
networks:
  db:
