version: "3"
services:
  backend:
    build: ./backend/
    environment:
      - MONGO_DB_URL=mongodb://mongo
      - SERVER_PORT=${BACKEND_SERVER_PORT}
      - LOG_LEVEL=${BACKEND_LOG_LEVEL}
    ports:
      - "${BACKEND_SERVER_PORT}:${BACKEND_SERVER_PORT}"
    networks:
      - db_net
    depends_on:
      - mongo
  mongo:
    image: "mongo:4.4.4"
    networks:
      - db_net
    ports:
      - "27017:27017"
networks:
  db_net:
